### ISSUE TITLE
Code doesn't get copied into the clipboard!

### ISSUE THREAD

**Issue by yash-dxt** [maheshmnj/neumorphic_design_flutter#1] opened 2020-07-09 08:20 UTC
I tried copying the text from the site, It does give the snack bar saying that it is copied onto the clipboard but it doesn't!

**Comment by maheshj01** [comment] 2020-07-09 14:36
Hi @udzhsay ,Thanks for taking your time to create the first issue,It seems the copy to clipboard isn't working on the mobile web.I will fix that soon.

**Comment by maheshj01** [comment] 2021-03-14 16:06
@yash-dxt can you check this seems to be resolved?
I am unable to reproduce this on chrome browser for android?

**Comment by yash-dxt** [comment] 2021-03-16 13:27
Doesn't work!

**Comment by maheshj01** [comment] 2021-03-17 03:42
I just published a fix with this commit 998f092fea1d1cbb31ad92e7c09484d4360ac5b6, And I tested on android,ios, mac os and windows desktop can you confirm now and also let me know what device you are testing on in case it doesn't work.
Thanks for taking your time.

**Comment by maheshj01** [comment] 2021-07-22 03:04
Closing this issue as fixed

**Closed as completed by maheshj01** 2021-07-22 03:04 UTC
Labels: bug, Customer Input
